# Generated by Django 4.1.2 on 2022-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=6)),
                ('categoria', models.CharField(max_length=6)),
                ('inventario_inicial', models.IntegerField()),
                ('inventario_recibido', models.IntegerField()),
                ('productos_vendido', models.IntegerField()),
            ],
        ),
    ]
