# Generated by Django 4.1.2 on 2022-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SetUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('codigo_producto', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='base',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='base',
            name='producto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='base',
            name='productos_vendido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
